CREATE TABLE "evals" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "rowid" INTEGER,
  "clerkship" TEXT,
  "submission_date" TEXT,
  "location" TEXT,
  "acad_yr" REAL,
  "rotation_date" TEXT,
  "summary_flg" TEXT,
  "evaluator" TEXT,
  "evaluator_id" REAL,
  "acad_title" TEXT,
  "learner_anon_id" TEXT,
  "pce_assign" TEXT,
  "society" TEXT,
  "acad_prog" TEXT,
  "acad_prog_trk" TEXT,
  "gender" TEXT,
  "urim_flg" TEXT,
  "age" REAL,
  "first_nbme_score" REAL,
  "question" TEXT,
  "answer_txt" TEXT,
  "answer_txt_redacted" TEXT
);
